version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookreader_web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn bookReader.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    container_name: bookreader_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    restart: always

  nginx:
    image: nginx:latest
    container_name: bookreader_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
